/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {} as const;

// Assignment contract names:
// - tokenA: PNPToken (PNPT)
// - tokenB: FNBToken (FNBT)
// - exchange: OrderBook
// Run Hardhat deploy to populate addresses and ABIs here.

export default deployedContracts satisfies GenericContractsDeclaration;
